### ISSUE TITLE
add mac friendly options in script (fix bashisms, file paths, need OSx tester)

### ISSUE THREAD

**Issue by tallguyjenks** [tallguyjenks/fla.sh#11]

**Comment by tallguyjenks** [comment]
@jhonkaman someone on reddit who was messing with the script got an answer for me... maybe.. what do you see in you `~/Library/Application Support` directory? are there data files in there used by programs?

**Comment by grokskookum** [comment]
Mac puts files here (example firefox)

myself:~ dznutz$ sudo find ~/Library/ -type f |grep -i firefox | cut -f 1-8 -d / | uniq -c |sort -n
   1 /Users/dznutz/Library//Application Support/Firefox/installs.ini
   1 /Users/dznutz/Library//Application Support/Firefox/profiles.ini
   1 /Users/dznutz/Library//Application Support/WebEx Folder/Add-ons
   1 /Users/dznutz/Library//Caches/org.mozilla.firefox/Cache.db
   1 /Users/dznutz/Library//Caches/org.mozilla.firefox/Cache.db-shm
   1 /Users/dznutz/Library//Caches/org.mozilla.firefox/Cache.db-wal
   1 /Users/dznutz/Library//Caches/org.mozilla.firefox/WebKitCache
   1 /Users/dznutz/Library//Preferences/org.mozilla.firefox.plist
   1 /Users/dznutz/Library//Saved Application State/org.mozilla.firefox.savedState/data.data
   1 /Users/dznutz/Library//Saved Application State/org.mozilla.firefox.savedState/window_1.data
   1 /Users/dznutz/Library//Saved Application State/org.mozilla.firefox.savedState/windows.plist
   3 /Users/dznutz/Library//Caches/Mozilla/updates
  14 /Users/dznutz/Library//Application Support/Firefox/Crash Reports
 529 /Users/dznutz/Library//Caches/Firefox/Profiles
2064 /Users/dznutz/Library//Application Support/Firefox/Profiles

**Comment by tallguyjenks** [comment]
lol @grokskookum, i dig the username haha. it looks like Library may be the place, your links have 2 slashes between library and things lke Application support, is there a missing field in there?

**Comment by jhonkaman** [comment]
@tallguyjenks there are a lot of folders in `~/Library/Application Support`. It looks like there is 1 folder for each application I have installed. If I look inside the folders, I see different types of files, but I do see a lot of `.plist` files, which I think fall under the category of data files that you're referring to.

**Comment by tallguyjenks** [comment]
@jhonkaman the single folder per application was probably what i was looking for. in that case, can you install the dependencies listed in the readme `fzf` and `bat`? and if so do they run as expected in your cli?

**Comment by jhonkaman** [comment]
Yes, I'll try installing them now.

**Comment by jhonkaman** [comment]
It looks like `fzf` and `bat` are working as expected, but I'm not sure how to get them to work together at the moment.

**Comment by tallguyjenks** [comment]
no need, the script should take care of that, but i need to adjust for mac, ill do that tonight, finishing my work day and errands at the moment

**Comment by tallguyjenks** [comment]
@jhonkaman or @grokskookum  what is the output of the `uname` command in your terminal, and also the `uname -s` command

**Comment by jhonkaman** [comment]
The output for both of those commands is `Darwin` for me.

**Comment by tallguyjenks** [comment]
excellent, then i may have a fix with a simple case statement. then ill need to you add the new script to a place in your $PATH then run it and see if anything breaks, will update you at that point

**Comment by tallguyjenks** [comment]
@jhonkaman can you run this command in your terminal `echo $HOME` and tell me the output, and what terminal emulator are you running? and also how did you install `fzf` and `bat` onto your machine?

**Comment by tallguyjenks** [comment]
@jhonkaman @grokskookum ive pushed a mac friendly version to master, please test and see if it works as expected. put the flash script in your $PATH somewhere and run it :)

**Comment by jhonkaman** [comment]
For your previous question, `echo $HOME` outputs `/Users/Javier`. 

The terminal emulator is just the built-in Terminal app on macOS. 

I installed fzf and bat using Homebrew. I'll try installing your script tomorrow.

**Comment by tallguyjenks** [comment]
perfect, if it works, then with homebrew installation of the 2 programs, we'll be good to go on mac!

**Comment by jhonkaman** [comment]
I got the following output when I ran `flash`:
```
/usr/local/bin/flash: line 108: [: /Users/Javier/Library/Application: binary operator expected
/usr/local/bin/flash: line 119: cd: /Users/Javier/Library/Application Support/flash: No such file or directory
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
touch: /Users/Javier/Library/Application Support/flash/.highscore: No such file or directory
touch: /Users/Javier/Library/Application Support/flash/.reviews: No such file or directory
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```
Maybe I messed up the installation.

**Comment by tallguyjenks** [comment]
@jhonkaman no i see what went wrong, the mac file path has a space in it and i didnt quote one of the instances of the variable holding the file path, i just fixed, grab the latest commit of the script and try again

**Comment by jhonkaman** [comment]
Got a little farther:
```
No .local/share/flash directory, make it? Y/N
y
touch: Support/flash/deck.csv: No such file or directory
touch: Support/flash/.highscore: No such file or directory
touch: Support/flash/.reviews: No such file or directory
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

**Comment by tallguyjenks** [comment]
@jhonkaman found'em, more unquoted paths, thanks apple... lol rinse and repeat, try again with latest build

**Comment by jhonkaman** [comment]
Ok. Still getting these errors:
```
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

**Comment by tallguyjenks** [comment]
okay try again, i switched some of the command substitution quoting

and can you post the output of `man find` for me?

**Comment by jhonkaman** [comment]
I think this page has the info you need for `man find`: https://www.freebsd.org/cgi/man.cgi?query=find&apropos=0&sektion=0&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html

**Comment by tallguyjenks** [comment]
well for the Darwin page, it says the `-maxdepth` option the way im using it is valid, i quoted the variable feeding it, so try again and see if the latest push works

**Comment by jhonkaman** [comment]
Ok I think that worked. This is what I see now. How do I get the sample deck?
```
No decks were found, please make a new deck
using : as a delimiter in a .csv file in
the .local/share/flash directory.

An example of a card:
Math:What is the square root of 4?:2:0
```

**Comment by tallguyjenks** [comment]
thats good, but not the answer that should have been displayed, can you `ls -la` the contents of the `~/Application Support/flash` directory?

i pushed some more changes to try after that too

**Comment by jhonkaman** [comment]
`ls -la`:
```
total 0
drwxr-xr-x   4 Javier  staff   128B Apr 27 13:19 ./
drwx------+ 88 Javier  staff   2.8K Apr 27 13:19 ../
-rw-r--r--   1 Javier  staff     0B Apr 27 13:19 .highscore
-rw-r--r--   1 Javier  staff     0B Apr 27 13:19 .reviews
```

**Comment by tallguyjenks** [comment]
okay so its not making the example deck like it should, did you re-run the latest commit: 46deb03

**Comment by jhonkaman** [comment]
Yes, I'm still getting the same output from above.

**Comment by tallguyjenks** [comment]
i think it may have been the use of variables in the brace expansion for OSx... maybe. moved some things around try latest build

**Comment by jhonkaman** [comment]
I tried the latest build, but I'm still getting the same output.

**Comment by tallguyjenks** [comment]
okay i have 2 more ideas for this issue. can you first test and anywhere in your system run `touch test.csv` and see if it is in fact creating the file

**Comment by jhonkaman** [comment]
`touch test.csv` does create a file.

**Comment by tallguyjenks** [comment]
alright i removed the brace expansion and just made individual touch commands, try build c8391d9

**Comment by jhonkaman** [comment]
Now I'm getting the previous error again:
```
find: illegal option -- m
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

No decks were found, please make a new deck
using : as a delimiter in a .csv file in
the /Users/Javier/Library/Application Support/flash directory.

An example of a card:
Math:What is the square root of 4?:2:0
```

**Comment by tallguyjenks** [comment]
god, mac is such a pain. try 9ab26d5

**Comment by jhonkaman** [comment]
I'm still getting the same output. I think this might be the issue: https://stackoverflow.com/questions/17548854/difference-between-mac-find-and-linux-find

**Comment by tallguyjenks** [comment]
@jhonkaman alright, i added the find path, lets see if the latest build works 0b1f60a

**Comment by jhonkaman** [comment]
Ok, that got rid of the error. Still getting this part:
```
No decks were found, please make a new deck
using : as a delimiter in a .csv file in
the /Users/Javier/Library/Application Support/flash directory.

An example of a card:
Math:What is the square root of 4?:2:0
```
If I had to guess, it looks like you're checking to see if any decks exist on line 124 and returning to the starting directory if there aren't any decks. I think you should add the `touch` command there from your `setup()` function to create the example deck.

**Comment by tallguyjenks** [comment]
first, can you remove the entire directory and all its contents and run it fresh? the script is meant to work on the first go, if it makes the directory but not the deck then it will be stuck until a deck is made, try a clean slate one more time

**Comment by tallguyjenks** [comment]
with build 
5c717b1

**Comment by jhonkaman** [comment]
Ok, tried it. Output:
```
No /Users/Javier/Library/Application Support/flash directory, make it? Y/N
y
touch: Support/flash/deck.csv: No such file or directory
touch: Support/flash/.highscore: No such file or directory
touch: Support/flash/.reviews: No such file or directory

No decks were found, please make a new deck
using : as a delimiter in a .csv file in
the /Users/Javier/Library/Application Support/flash directory.

An example of a card:
Math:What is the square root of 4?:2:0
```

**Comment by tallguyjenks** [comment]
Progress! i get it now, i think i need to escape the spaces in the double quoted strings, new build coming in one sec.... okay: 23baa6d

**Comment by jhonkaman** [comment]
Ok, now I'm getting two things:
```
No /Users/Javier/Library/Application\ Support/flash directory, make it? Y/N
y
mkdir: /Users/Javier/Library/Application\ Support: No such file or directory
/usr/local/bin/flash: line 121: cd: /Users/Javier/Library/Application\ Support/flash: No such file or directory
touch: /Users/Javier/Library/Application\ Support/flash/.highscore: No such file or directory
touch: /Users/Javier/Library/Application\ Support/flash/.reviews: No such file or directory
/usr/local/bin/flash: line 147: shuf: command not found
```
And:
```
\e[1mCards Reviewed:\e[1m	0
cat: /Users/Javier/Library/Application\ Support/flash/.highscore: No such file or directory
    \e[1mHigh Score:\e[1m	
awk: can't open file /Users/Javier/Library/Application\ Support/flash/.reviews
 source line number 1
    \e[1mAvg review:\e[1m	

Category:
        
Question:
```
Also it says `.//test.csv` on the actual flashcard screen:
<img width="1073" alt="Screen Shot 2020-05-02 at 1 14 04 PM" src="https://user-images.githubusercontent.com/8496422/80891156-25b77b80-8c77-11ea-9b70-c0ecea0b36bb.png">

**Comment by jhonkaman** [comment]
I installed `coreutils` and tried the latest version, but got this error:
```
No HOME/Library/Application Support/flash directory, make it? Y/N
y
mkdir: HOME/Library/Application Support: No such file or directory
/usr/local/bin/flash: line 133: cd: HOME/Library/Application Support/flash: No such file or directory
```

**Comment by tallguyjenks** [comment]
@jhonkaman found it, it was a missing `$` for the mac file path `$HOME` variable. and fixed another issue with the installation of coreutils shuf is installed as gshuf so i alias it in the script to retain functionality. test latest build

**Comment by jhonkaman** [comment]
Latest output:
```
No /Users/Javier/Library/Application Support/flash directory, make it? Y/N
y
touch: Support/flash/deck.csv: No such file or directory
touch: Support/flash/.highscore: No such file or directory
touch: Support/flash/.reviews: No such file or directory
```

**Comment by jhonkaman** [comment]
Also, does it matter if my shell is zsh?

**Comment by tallguyjenks** [comment]
yeah it matters, zsh breaks scripts with bashisms im not sure if thats whats happening or not though..

**Comment by jsnal** [comment]
It shouldn't matter if your shell is zsh. Your script includes a shebang line at the top, so as long as you're invoking the file using `source` or `./` it will use the interpreter in the shebang line. In this case, it's in your path so it's essentially sourcing it.

Seems like the way `deck.csv` (and the other two) is being appended to `$DIR` could be the problem. However, it seems right to me. Maybe it works differently when concatenating strings with spaces?

**Comment by tallguyjenks** [comment]
@jsnal thats what im thinking and im unsure about how to make it work at this point, i tried to escape the space but IIRC that breaks the file path

**Comment by jsnal** [comment]
Alright so I did some testing and it seems like if you remove `eval` from your touch statement it works as expected. I tested it with Linux and macOS 10.14.6 (Mojave) and it seems to install everything fine. Why are you using `eval` there?

**Comment by tallguyjenks** [comment]
originally it was helping with another issue or so i thought, but if
removing it makes it function as expected, wanna send a pull request? :)
and thanks for testing! this is great if it now works on macOS!
