### ISSUE TITLE
add option to first look at $XDG_DATA_HOME before another directory for file placement

### ISSUE THREAD

**Issue by tallguyjenks** [tallguyjenks/fla.sh#17]
- [ ] need to see if man even uses XDG
- [ ] test on my system
- [ ] test program on windows

**Comment by sobrinojulian** [comment]
Hi! you can do like this: `${$XDG_DATA_HOME:-$HOME/.local/share}`
if the env variable does not exist, then it uses `.local/share`.
You can read more about the  XDG Base Directory specification [here](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

**Comment by tallguyjenks** [comment]
@sobrinojulian  Excellent! thanks for the link too, ive been meaning to look into the XDG stuff

**Comment by tallguyjenks** [comment]
@sobrinojulian when i tried to add the substitution to my script and run to test i get this output: `./flash: line 52: ${$XDG_DATA_HOME:-$HOME/.local/share}/flash: bad substitution` its properly quotes and looks like several other functioning examples ive seen, any ideas?

**Comment by sobrinojulian** [comment]
@tallguyjenks Yes! Im sorry, tthat snippet is wrong. Drop the `$` Before XDG:
$**{X**DG_DATA_HOME:-$HOME/.local/share}

**Comment by tallguyjenks** [comment]
@sobrinojulian that did it, thank you very much!
