### ISSUE TITLE
Changing flash card format from CSV

### ISSUE THREAD

**Issue by Gavinok** [tallguyjenks/fla.sh#29]
**Describe the solution you'd like**
Currently I feel like the project is being limited by the use of CSV as its storage format since even when multiple lines can be supported it would be really difficult to read the question. This also limits how much formating the question/answer can have.

**Describe alternatives you've considered**
Currently I was thinking of something like markdown. I also think making each flash card as a file would make the parsing a lot easier.

**Comment by tallguyjenks** [comment]
so we had ideas for the data interchange format being:
- **Markdown**
    + _Pros_
        * Easily works with pandoc
        * Ubiquitous syntax
        * easy to parse
        * potential functionality with yaml front matter?
    + _Cons_
        * a file for each card instead of 1 data file
        * in dealing with markdown how many other software dependencies are we going to generate?
- **JSON**
    + _pros_
        * common format for data
        * a single file containing all structured data
    + _cons_
        * would need to program a way to insert new cards or remove/update them as the users would then need to know json to effectively edit them
        * would need to parse json with bash?
- **TSV**
    + _pros_
        * still plain text
        * better than a text character for separating fields visually
    + _cons_
        * still single lines and basically the same existing functionality

**Comment by Gavinok** [comment]
@tallguyjenks 

# Markdown
Both options don't actually require each flashcard to be it's own file but it would make parsing alot easier.

## Option 1
- using awk and sed to translate the markdown to nroff that way we could just output to the tty, a pdf, or even html.
- only the added dependency of nroff. (Available on most systems)

### Note
I'm a bit biased as I use troff all the time for writing math notes and other typesetting.

## Option 2
- An alternative would also be to just use terminal escape sequences for the markdown syntax.
- There bash based are a few markdown to html parsers that could be used for a regex reference. 
- Could later add groff support for outputting pdfs and html.

# JSON
This would make parsing easier and allow need features to be optionally added without breaking old flash cards by adding new keys as the project develops.

- For JSON there is the beautiful program jq that I highly recommend for JSON parsing. 
- There is also a way to parse JSON using perl which comes with most Unix systems.

# TSV
Honestly I only see negatives when it comes to dealing with tsv files.

- Tabs aren't something you can distinguish from spaces. One example would be using diff.
- It still makes multiline flash cards hard to read.

# Blocks Of Text
One way to do this would be one block is a question the next block is an answer. own file. 
- Pros
  - Easy to parse
  - Minimal formatting for users to learn
  - Possibly integration with suckless's sent
- Cons
  - Adding extra features could be difficult without breaking functionality.

Let me know what you think.

**Comment by tallguyjenks** [comment]
@Gavinok for now i think im interested in these: 

----

# Markdown

Both options don't actually require each flashcard to be it's own file but it would make parsing alot easier.

## Option 1

- using awk and sed to translate the markdown to nroff that way we could just output to the tty, a pdf, or even html.
- only the added dependency of nroff. (Available on most systems)

----

and this

----

# Blocks Of Text
One way to do this would be one block is a question the next block is an answer. own file.

- Pros
    + Easy to parse
    + Minimal formatting for users to learn
    + Possibly integration with suckless's sent
- Cons
    + Adding extra features could be difficult without breaking functionality.

----

I do want to look at Sent a little and play around with it before i make a choice but both options sound promising

**Comment by tallguyjenks** [comment]
im liking sent for the displaying but i can see getting LaTeX math into it being a bit more tedious by setting up a workflow to export rendered formulas to png and then loading pngs into sent. I like sent though, this gave me a good opportunity to play with it.

i think messing with the `*roff` formats would be preferable. 

what are your thoughts on all of it?

**Comment by tallguyjenks** [comment]
plus if we could make use of the yaml front matter in a file if each card is its own file, we could use that for the point system? or more closely imitate the anki system of using actual date time for date time repetition.

**Comment by tallguyjenks** [comment]
found a cool AUR program `tex2png` if we went with `sent` we could always just set up a workflow with `tex2png "$\frac{1+1}{\pi}$"` which would generate .pngs that could be loaded into `sent` .... damn man, there's too much good technology around! lol

**Comment by Gavinok** [comment]
The tex2png thing sounds cool but it may be a bit of obscure dependency don't you think?

**Comment by Gavinok** [comment]
Based on the sound of it I'm thinking the markdown format would be a pretty good option. Any ideas on how to seperate each cards question and answer.

**Comment by tallguyjenks** [comment]
@Gavinok could use the markdown horizontal rule `----`?
