### ISSUE TITLE
Slashes (/) will prevent the card from adding up points.

### ISSUE THREAD

**Issue by gnstaxo** [tallguyjenks/fla.sh#30]
**Describe the bug**
If you have a slash (/) in a card's answer or question, its points field won't the altered.

**To Reproduce**
1. Add a card like this to one of your decks:
`Vocabulary:burst out laughing/crying:to suddenly start laughing/crying. I walked in and everyone burst out laughing:0`
2. Start the deck from fla.sh normally.
3. When the card containing slash shows up, press enter and press 4 or 5.
4. Exit the program.
5. Open the deck file.
4. And so you see the error, the field that's supposed to be 1 or 2 didn't change (it's 0).

**Expected behavior**
To add up points.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - st
 - mksh (tried in bash too)

---

By filing an issue to this repo, I promise that

- [x] I have provided the necessary information about my bug report
- [x] I have downloaded the latest version of this repo and reproduced my issue with the latest version
- [x] If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by tallguyjenks** [comment]
replicated. very interesting. looking into this

**Comment by tallguyjenks** [comment]
the scores are updated with a `sed` command i think the forward slashed are messing with the behavior of the regex replacement of the score.

**Comment by gnstaxo** [comment]
> the scores are updated with a `sed` command i think the forward slashed are messing with the behavior of the regex replacement of the score.

I think so. [ and ] cause the same unintended effect.

**Comment by tallguyjenks** [comment]
those special characters man. downside of this program being written in bash lol

**Comment by gnstaxo** [comment]
```sh
QUESTION_REGEX=$(sed "s/\(\/\|\[\|\]\)/\\\\\1/g" <<< ${q[1]})
ANSWER_REGEX=$(sed "s/\(\/\|\[\|\]\)/\\\\\1/g" <<< ${q[2]})

# Update item score for each flashcard item
sed -i "s/${q[0]}:$QUESTION_REGEX:$ANSWER_REGEX:${q[3]}/${q[0]}:$QUESTION_REGEX:$ANSWER_REGEX:$NEW_ITEM_SCORE/g" "$DECK"
```
